
#commands that specify the language

language: python
python:
- "3.5"

#command that installs dependancies
pip install -r requirements.txt

#command that runs tests
script:
- pytest --cov-report term missing --cov=app

after_success:
- coveralls
