
#commands that specify the language

language: python
python:
- "3.5"
#command that installs dependancies
install:
- pip install -r requirements.txt
#command that runs tests
script:
-  nosetests --exe -v --with-coverage --cover-package=app


after_success:
- coveralls
