#commands that specify the language

language: python

python:
- "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install pytest-cov

script:
 - coverage run -m --source api pytest
 - python -m coverage report -m
 - coveralls




